services:
  web:
    image: nginx:latest
    ports:
      - "82:80"

    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./php/Dockerfile

    volumes:
      - ./app:/var/www/html

    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}

  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql

    ports:
      - "3307:3306"

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  cache:
    image: redis:latest

    ports:
      - "6379:6379"

volumes:
  mysqldata:
