services:
  web:
    image: nginx:latest
    ports:
      - "82:80"

    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./php/Dockerfile

    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html

  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql

    ports:
      - "3307:3306"

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

volumes:
  mysqldata:
