name: TranslateThis
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Docker Username length
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: echo "Docker Username length ${#DOCKER_USERNAME}"
            - name: Echo Docker username
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: echo "Docker Username is ${{ DOCKER_USERNAME }}"
            - uses: actions/checkout@v3
            - name: Install Composer Dependencies
              working-directory: ./app
              run: composer install --prefer-dist
            - name: Run Tests
              working-directory: ./app
              run: composer run-phpunit
            - run: docker build --target app -t bakedbean78/php-composer:1.1 -f ./php/Dockerfile .
            - run: docker build -t bakedbean78/nginx-php:1.0 -f ./nginx/Dockerfile .
            - name: Push Docker image
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push bakedbean78/php-composer:1.1
            - run: docker push bakedbean78/nginx-php:1.0